# Generated by Django 3.0.3 on 2020-02-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default', upload_to='profile_pics'),
        ),
    ]
